export { default as useResistancesBrowse } from '@/use/useApi/resistance/browse'
export { default as useResistancesGet } from '@/use/useApi/resistance/get'
export { default as useResistancesEdit } from '@/use/useApi/resistance/edit'
export { default as useResistancesCreate } from '@/use/useApi/resistance/create'
export { default as useResistancesDelete } from '@/use/useApi/resistance/delete'
