export { default as useOriginsBrowse } from '@/use/useApi/origin/browse'
export { default as useOriginsGet } from '@/use/useApi/origin/get'
export { default as useOriginsEdit } from '@/use/useApi/origin/edit'
export { default as useOriginsCreate } from '@/use/useApi/origin/create'
export { default as useOriginsDelete } from '@/use/useApi/origin/delete'
