export { default as useWatchesNews } from '@/use/useApi/watch/news'
export { default as useWatchesBrowse } from '@/use/useApi/watch/browse'
export { default as useWatchesGet } from '@/use/useApi/watch/get'
export { default as useWatchesEdit } from '@/use/useApi/watch/edit'
export { default as useWatchesCreate } from '@/use/useApi/watch/create'
export { default as useWatchesDelete } from '@/use/useApi/watch/delete'
